export const availableAdUnits = [
    {
        game_key:
            "2e693494-9c8b-4787-b2ea-f175340ce907/d6dc415f-f506-4f9a-90d5-3935e281cdbf",
        lorenzo_id: "4f1b9670-88a3-422a-a37e-9a845ee20c44",
        region: "eu-west-1",
        environment: "MWEB",
        service_level: "managed",
        width: 300,
        height: 250,
        redirect_urls: [
            "%%TTD_CLK%%https://www.sainsburys.co.uk/gol-ui/product/good-guys-bakehouse-cheddar-biscuit-melts-50g",
            "%%TTD_CLK%%https://www.sainsburys.co.uk/gol-ui/product/good-guys-bakehouse-peppered-biscuit-melts-50g",
        ],
        third_party_engagement: [
            "https://pixel.adsafeprotected.com/jload?anId=930756&advId=%%TTD_ADVERTISERID%%_ENG&campId=%%TTD_CAMPAIGNID%%_ENG&pubId=%%TTD_SUPPLYVENDOR%%_ENG&chanId=%%TTD_ADGROUPID%%_ENG&placementId=%%TTD_CREATIVEID%%_ENG&dealId=%%TTD_DEALID%%_ENG&adsafe_par&bidurl=%%TTD_SITE%%",
        ],
        dsp: "TTD",
        ttd_imp_aud_user_ttl_min: "86400",
        ttd_adformat: "%%TTD_ADFORMAT%%",
        ttd_adgroupid: "%%TTD_ADGROUPID%%",
        ttd_advertiserid: "%%TTD_ADVERTISERID%%",
        ttd_all_categories: "%%TTD_ALL_CATEGORIES%%",
        ttd_base_bid_override_metadata: "%%TTD_BASE_BID_OVERRIDE_METADATA%%",
        ttd_campaignid: "%%TTD_CAMPAIGNID%%",
        ttd_category: "%%TTD_CATEGORY%%",
        ttd_city: "%%TTD_CITY%%",
        ttd_country: "%%TTD_COUNTRY%%",
        ttd_creativeid: "%%TTD_CREATIVEID%%",
        ttd_dealid: "%%TTD_DEALID%%",
        ttd_deviceosfamily: "%%TTD_DEVICEOSFAMILY%%",
        ttd_devicetype: "%%TTD_DEVICETYPE%%",
        ttd_devicemake: "%%TTD_DEVICEMAKE%%",
        ttd_devicemodel: "%%TTD_DEVICEMODEL%%",
        ttd_gdpr_applies: "%%TTD_GDPR_APPLIES%%",
        ttd_gdpr_consent_strinG: "%%TTD_GDPR_CONSENT_STRING%%",
        ttd_impressionid: "%%TTD_IMPRESSIONID%%",
        ttd_language: "%%TTD_LANGUAGE%%",
        ttd_metro: "%%TTD_METRO%%",
        ttd_partnerid: "%%TTD_PARTNERID%%",
        ttd_privatecontractid: "%%TTD_PRIVATECONTRACTID%%",
        ttd_publisherid: "%%TTD_PUBLISHERID%%",
        ttd_region: "%%TTD_REGION%%",
        ttd_rendering_context: "%%TTD_RENDERING_CONTEXT%%",
        ttd_site: "%%TTD_SITE%%",
        ttd_site_with_path: "%%TTD_SITE_WITH_PATH%%",
        ttd_supplyvendor: "%%TTD_SUPPLYVENDOR%%",
        ttd_tdid: "%%TTD_TDID%%",
        ttd_trustesid: "%%TTD_TRUSTESID%%",
        ttd_unix_timestamp: "%%TTD_UNIX_TIMESTAMP%%",
        ttd_zipcode: "%%TTD_ZIPCODE%%",
    },
    {
        game_key:
            "a5c1b6b9d8907ab19d8bb3610d8ea923/e15d29d6b1137115c06d7d5ac6e21c12",
        lorenzo_id: "4f1b9670-88a3-422a-a37e-9a845ee20c44",
        region: "eu-west-1",
        environment: "MWEB",
        service_level: "managed",
        width: 320,
        height: 480,
        redirect_urls: [
            "%%TTD_CLK%%https://www.sainsburys.co.uk/gol-ui/product/good-guys-bakehouse-cheddar-biscuit-melts-50g",
            "%%TTD_CLK%%https://www.sainsburys.co.uk/gol-ui/product/good-guys-bakehouse-peppered-biscuit-melts-50g",
        ],
        third_party_engagement: [
            "https://pixel.adsafeprotected.com/jload?anId=930756&advId=%%TTD_ADVERTISERID%%_ENG&campId=%%TTD_CAMPAIGNID%%_ENG&pubId=%%TTD_SUPPLYVENDOR%%_ENG&chanId=%%TTD_ADGROUPID%%_ENG&placementId=%%TTD_CREATIVEID%%_ENG&dealId=%%TTD_DEALID%%_ENG&adsafe_par&bidurl=%%TTD_SITE%%",
        ],
        dsp: "TTD",
        ttd_imp_aud_user_ttl_min: "86400",
        ttd_adformat: "%%TTD_ADFORMAT%%",
        ttd_adgroupid: "%%TTD_ADGROUPID%%",
        ttd_advertiserid: "%%TTD_ADVERTISERID%%",
        ttd_all_categories: "%%TTD_ALL_CATEGORIES%%",
        ttd_base_bid_override_metadata: "%%TTD_BASE_BID_OVERRIDE_METADATA%%",
        ttd_campaignid: "%%TTD_CAMPAIGNID%%",
        ttd_category: "%%TTD_CATEGORY%%",
        ttd_city: "%%TTD_CITY%%",
        ttd_country: "%%TTD_COUNTRY%%",
        ttd_creativeid: "%%TTD_CREATIVEID%%",
        ttd_dealid: "%%TTD_DEALID%%",
        ttd_deviceosfamily: "%%TTD_DEVICEOSFAMILY%%",
        ttd_devicetype: "%%TTD_DEVICETYPE%%",
        ttd_devicemake: "%%TTD_DEVICEMAKE%%",
        ttd_devicemodel: "%%TTD_DEVICEMODEL%%",
        ttd_gdpr_applies: "%%TTD_GDPR_APPLIES%%",
        ttd_gdpr_consent_strinG: "%%TTD_GDPR_CONSENT_STRING%%",
        ttd_impressionid: "%%TTD_IMPRESSIONID%%",
        ttd_language: "%%TTD_LANGUAGE%%",
        ttd_metro: "%%TTD_METRO%%",
        ttd_partnerid: "%%TTD_PARTNERID%%",
        ttd_privatecontractid: "%%TTD_PRIVATECONTRACTID%%",
        ttd_publisherid: "%%TTD_PUBLISHERID%%",
        ttd_region: "%%TTD_REGION%%",
        ttd_rendering_context: "%%TTD_RENDERING_CONTEXT%%",
        ttd_site: "%%TTD_SITE%%",
        ttd_site_with_path: "%%TTD_SITE_WITH_PATH%%",
        ttd_supplyvendor: "%%TTD_SUPPLYVENDOR%%",
        ttd_tdid: "%%TTD_TDID%%",
        ttd_trustesid: "%%TTD_TRUSTESID%%",
        ttd_unix_timestamp: "%%TTD_UNIX_TIMESTAMP%%",
        ttd_zipcode: "%%TTD_ZIPCODE%%",
    },
    {
        game_key:
            "c963c609-fa2f-4790-a8c8-8310054a252f/46cc0721-159d-407b-afc9-5a2fe54f4ef3",
        lorenzo_id: "9e813ae8-9791-462c-a059-78200ff171ed",
        region: "eu-west-1",
        environment: "MWEB",
        service_level: "managed",
        width: 320,
        height: 480,
        redirect_urls: ["%%TTD_CLK%%https://www.mcdonalds.com.br/pedidos"],
        third_party_engagement: [
            "https://pixel.adsafeprotected.com/jload?anId=930756&advId=%%TTD_ADVERTISERID%%_ENG&campId=%%TTD_CAMPAIGNID%%_ENG&pubId=%%TTD_SUPPLYVENDOR%%_ENG&chanId=%%TTD_ADGROUPID%%_ENG&placementId=%%TTD_CREATIVEID%%_ENG&dealId=%%TTD_DEALID%%_ENG&adsafe_par&bidurl=%%TTD_SITE%%",
        ],
        dsp: "TTD",
        ttd_imp_aud_user_ttl_min: "86400",
        ttd_adformat: "%%TTD_ADFORMAT%%",
        ttd_adgroupid: "%%TTD_ADGROUPID%%",
        ttd_advertiserid: "%%TTD_ADVERTISERID%%",
        ttd_all_categories: "%%TTD_ALL_CATEGORIES%%",
        ttd_base_bid_override_metadata: "%%TTD_BASE_BID_OVERRIDE_METADATA%%",
        ttd_campaignid: "%%TTD_CAMPAIGNID%%",
        ttd_category: "%%TTD_CATEGORY%%",
        ttd_city: "%%TTD_CITY%%",
        ttd_country: "%%TTD_COUNTRY%%",
        ttd_creativeid: "%%TTD_CREATIVEID%%",
        ttd_dealid: "%%TTD_DEALID%%",
        ttd_deviceosfamily: "%%TTD_DEVICEOSFAMILY%%",
        ttd_devicetype: "%%TTD_DEVICETYPE%%",
        ttd_devicemake: "%%TTD_DEVICEMAKE%%",
        ttd_devicemodel: "%%TTD_DEVICEMODEL%%",
        ttd_gdpr_applies: "%%TTD_GDPR_APPLIES%%",
        ttd_gdpr_consent_strinG: "%%TTD_GDPR_CONSENT_STRING%%",
        ttd_impressionid: "%%TTD_IMPRESSIONID%%",
        ttd_language: "%%TTD_LANGUAGE%%",
        ttd_metro: "%%TTD_METRO%%",
        ttd_partnerid: "%%TTD_PARTNERID%%",
        ttd_privatecontractid: "%%TTD_PRIVATECONTRACTID%%",
        ttd_publisherid: "%%TTD_PUBLISHERID%%",
        ttd_region: "%%TTD_REGION%%",
        ttd_rendering_context: "%%TTD_RENDERING_CONTEXT%%",
        ttd_site: "%%TTD_SITE%%",
        ttd_site_with_path: "%%TTD_SITE_WITH_PATH%%",
        ttd_supplyvendor: "%%TTD_SUPPLYVENDOR%%",
        ttd_tdid: "%%TTD_TDID%%",
        ttd_trustesid: "%%TTD_TRUSTESID%%",
        ttd_unix_timestamp: "%%TTD_UNIX_TIMESTAMP%%",
        ttd_zipcode: "%%TTD_ZIPCODE%%",
    },
    {
        game_key:
            "a1f64621-3000-4a80-a0c5-61ee45e923b6/89278899-f383-4225-b902-61dafb43f6c1",
        lorenzo_id: "bacbc32f-f8e1-4990-afe7-1b9b5da61722",
        region: "eu-west-1",
        environment: "MWEB",
        service_level: "managed",
        width: 320,
        height: 480,
        redirect_urls: [
            "%%TTD_CLK%%https://www.inspiringtravel.co.uk/?newsletter=true",
        ],
        third_party_engagement: [
            "https://pixel.adsafeprotected.com/jload?anId=930756&advId=%%TTD_ADVERTISERID%%_ENG&campId=%%TTD_CAMPAIGNID%%_ENG&pubId=%%TTD_SUPPLYVENDOR%%_ENG&chanId=%%TTD_ADGROUPID%%_ENG&placementId=%%TTD_CREATIVEID%%_ENG&dealId=%%TTD_DEALID%%_ENG&adsafe_par&bidurl=%%TTD_SITE%%",
        ],
        dsp: "TTD",
        ttd_imp_aud_user_ttl_min: "86400",
        ttd_adformat: "%%TTD_ADFORMAT%%",
        ttd_adgroupid: "%%TTD_ADGROUPID%%",
        ttd_advertiserid: "%%TTD_ADVERTISERID%%",
        ttd_all_categories: "%%TTD_ALL_CATEGORIES%%",
        ttd_base_bid_override_metadata: "%%TTD_BASE_BID_OVERRIDE_METADATA%%",
        ttd_campaignid: "%%TTD_CAMPAIGNID%%",
        ttd_category: "%%TTD_CATEGORY%%",
        ttd_city: "%%TTD_CITY%%",
        ttd_country: "%%TTD_COUNTRY%%",
        ttd_creativeid: "%%TTD_CREATIVEID%%",
        ttd_dealid: "%%TTD_DEALID%%",
        ttd_deviceosfamily: "%%TTD_DEVICEOSFAMILY%%",
        ttd_devicetype: "%%TTD_DEVICETYPE%%",
        ttd_devicemake: "%%TTD_DEVICEMAKE%%",
        ttd_devicemodel: "%%TTD_DEVICEMODEL%%",
        ttd_gdpr_applies: "%%TTD_GDPR_APPLIES%%",
        ttd_gdpr_consent_strinG: "%%TTD_GDPR_CONSENT_STRING%%",
        ttd_impressionid: "%%TTD_IMPRESSIONID%%",
        ttd_language: "%%TTD_LANGUAGE%%",
        ttd_metro: "%%TTD_METRO%%",
        ttd_partnerid: "%%TTD_PARTNERID%%",
        ttd_privatecontractid: "%%TTD_PRIVATECONTRACTID%%",
        ttd_publisherid: "%%TTD_PUBLISHERID%%",
        ttd_region: "%%TTD_REGION%%",
        ttd_rendering_context: "%%TTD_RENDERING_CONTEXT%%",
        ttd_site: "%%TTD_SITE%%",
        ttd_site_with_path: "%%TTD_SITE_WITH_PATH%%",
        ttd_supplyvendor: "%%TTD_SUPPLYVENDOR%%",
        ttd_tdid: "%%TTD_TDID%%",
        ttd_trustesid: "%%TTD_TRUSTESID%%",
        ttd_unix_timestamp: "%%TTD_UNIX_TIMESTAMP%%",
        ttd_zipcode: "%%TTD_ZIPCODE%%",
    },
    {
        game_key: "afb8688bf142ebab/f13621b1319a1705",
        adludio_brief_ref: "",
        region: "eu-west-1",
        environment: "MWEB",
        service_level: "managed",
        width: 320,
        height: 480,
        redirect_urls: [
            "%%TTD_CLK%%https://www.youtube.com/watch?v=QgXUOzZQtkQ",
        ],
        third_party_engagement: [
            "https://pixel.adsafeprotected.com/jload?anId=930756&advId=%%TTD_ADVERTISERID%%_ENG&campId=%%TTD_CAMPAIGNID%%_ENG&pubId=%%TTD_SUPPLYVENDOR%%_ENG&chanId=%%TTD_ADGROUPID%%_ENG&placementId=%%TTD_CREATIVEID%%_ENG&dealId=%%TTD_DEALID%%_ENG&adsafe_par&bidurl=%%TTD_SITE%%",
        ],
        dsp: "TTD",
        ttd_imp_aud_user_ttl_min: "86400",
        ttd_adformat: "%%TTD_ADFORMAT%%",
        ttd_adgroupid: "%%TTD_ADGROUPID%%",
        ttd_advertiserid: "%%TTD_ADVERTISERID%%",
        ttd_all_categories: "%%TTD_ALL_CATEGORIES%%",
        ttd_base_bid_override_metadata: "%%TTD_BASE_BID_OVERRIDE_METADATA%%",
        ttd_campaignid: "%%TTD_CAMPAIGNID%%",
        ttd_category: "%%TTD_CATEGORY%%",
        ttd_city: "%%TTD_CITY%%",
        ttd_country: "%%TTD_COUNTRY%%",
        ttd_creativeid: "%%TTD_CREATIVEID%%",
        ttd_dealid: "%%TTD_DEALID%%",
        ttd_deviceosfamily: "%%TTD_DEVICEOSFAMILY%%",
        ttd_devicetype: "%%TTD_DEVICETYPE%%",
        ttd_devicemake: "%%TTD_DEVICEMAKE%%",
        ttd_devicemodel: "%%TTD_DEVICEMODEL%%",
        ttd_gdpr_applies: "%%TTD_GDPR_APPLIES%%",
        ttd_gdpr_consent_strinG: "%%TTD_GDPR_CONSENT_STRING%%",
        ttd_impressionid: "%%TTD_IMPRESSIONID%%",
        ttd_language: "%%TTD_LANGUAGE%%",
        ttd_metro: "%%TTD_METRO%%",
        ttd_partnerid: "%%TTD_PARTNERID%%",
        ttd_privatecontractid: "%%TTD_PRIVATECONTRACTID%%",
        ttd_publisherid: "%%TTD_PUBLISHERID%%",
        ttd_region: "%%TTD_REGION%%",
        ttd_rendering_context: "%%TTD_RENDERING_CONTEXT%%",
        ttd_site: "%%TTD_SITE%%",
        ttd_site_with_path: "%%TTD_SITE_WITH_PATH%%",
        ttd_supplyvendor: "%%TTD_SUPPLYVENDOR%%",
        ttd_tdid: "%%TTD_TDID%%",
        ttd_trustesid: "%%TTD_TRUSTESID%%",
        ttd_unix_timestamp: "%%TTD_UNIX_TIMESTAMP%%",
        ttd_zipcode: "%%TTD_ZIPCODE%%",
    },
    {
        game_key: "34779f343f1db6ec/bbcf889cfdf0aa0f",
        adludio_brief_ref: "",
        region: "eu-west-1",
        environment: "MWEB",
        service_level: "managed",
        width: 320,
        height: 480,
        redirect_urls: [
            "%%TTD_CLK%%https://www.amazon.in/stores/page/F2B78120-F96F-46C3-8706-6B2ECF0D7B09?channel=IPA",
        ],
        third_party_engagement: [
            "https://pixel.adsafeprotected.com/jload?anId=930756&advId=%%TTD_ADVERTISERID%%_ENG&campId=%%TTD_CAMPAIGNID%%_ENG&pubId=%%TTD_SUPPLYVENDOR%%_ENG&chanId=%%TTD_ADGROUPID%%_ENG&placementId=%%TTD_CREATIVEID%%_ENG&dealId=%%TTD_DEALID%%_ENG&adsafe_par&bidurl=%%TTD_SITE%%",
        ],
        dsp: "TTD",
        ttd_imp_aud_user_ttl_min: "86400",
        ttd_adformat: "%%TTD_ADFORMAT%%",
        ttd_adgroupid: "%%TTD_ADGROUPID%%",
        ttd_advertiserid: "%%TTD_ADVERTISERID%%",
        ttd_all_categories: "%%TTD_ALL_CATEGORIES%%",
        ttd_base_bid_override_metadata: "%%TTD_BASE_BID_OVERRIDE_METADATA%%",
        ttd_campaignid: "%%TTD_CAMPAIGNID%%",
        ttd_category: "%%TTD_CATEGORY%%",
        ttd_city: "%%TTD_CITY%%",
        ttd_country: "%%TTD_COUNTRY%%",
        ttd_creativeid: "%%TTD_CREATIVEID%%",
        ttd_dealid: "%%TTD_DEALID%%",
        ttd_deviceosfamily: "%%TTD_DEVICEOSFAMILY%%",
        ttd_devicetype: "%%TTD_DEVICETYPE%%",
        ttd_devicemake: "%%TTD_DEVICEMAKE%%",
        ttd_devicemodel: "%%TTD_DEVICEMODEL%%",
        ttd_gdpr_applies: "%%TTD_GDPR_APPLIES%%",
        ttd_gdpr_consent_strinG: "%%TTD_GDPR_CONSENT_STRING%%",
        ttd_impressionid: "%%TTD_IMPRESSIONID%%",
        ttd_language: "%%TTD_LANGUAGE%%",
        ttd_metro: "%%TTD_METRO%%",
        ttd_partnerid: "%%TTD_PARTNERID%%",
        ttd_privatecontractid: "%%TTD_PRIVATECONTRACTID%%",
        ttd_publisherid: "%%TTD_PUBLISHERID%%",
        ttd_region: "%%TTD_REGION%%",
        ttd_rendering_context: "%%TTD_RENDERING_CONTEXT%%",
        ttd_site: "%%TTD_SITE%%",
        ttd_site_with_path: "%%TTD_SITE_WITH_PATH%%",
        ttd_supplyvendor: "%%TTD_SUPPLYVENDOR%%",
        ttd_tdid: "%%TTD_TDID%%",
        ttd_trustesid: "%%TTD_TRUSTESID%%",
        ttd_unix_timestamp: "%%TTD_UNIX_TIMESTAMP%%",
        ttd_zipcode: "%%TTD_ZIPCODE%%",
    },
    {
        game_key: "34779f343f1db6ec/dfdf889cfdf0aaf6",
        adludio_brief_ref: "",
        region: "eu-west-1",
        environment: "MWEB",
        service_level: "managed",
        width: 320,
        height: 480,
        redirect_urls: [
            "%%TTD_CLK%%https://www.amazon.in/stores/page/6A6FD26B-F854-4C7E-92D9-B5B039AB97F2?channel=DigiAd",
        ],
        third_party_engagement: [
            "https://pixel.adsafeprotected.com/jload?anId=930756&advId=%%TTD_ADVERTISERID%%_ENG&campId=%%TTD_CAMPAIGNID%%_ENG&pubId=%%TTD_SUPPLYVENDOR%%_ENG&chanId=%%TTD_ADGROUPID%%_ENG&placementId=%%TTD_CREATIVEID%%_ENG&dealId=%%TTD_DEALID%%_ENG&adsafe_par&bidurl=%%TTD_SITE%%",
        ],
        dsp: "TTD",
        ttd_imp_aud_user_ttl_min: "86400",
        ttd_adformat: "%%TTD_ADFORMAT%%",
        ttd_adgroupid: "%%TTD_ADGROUPID%%",
        ttd_advertiserid: "%%TTD_ADVERTISERID%%",
        ttd_all_categories: "%%TTD_ALL_CATEGORIES%%",
        ttd_base_bid_override_metadata: "%%TTD_BASE_BID_OVERRIDE_METADATA%%",
        ttd_campaignid: "%%TTD_CAMPAIGNID%%",
        ttd_category: "%%TTD_CATEGORY%%",
        ttd_city: "%%TTD_CITY%%",
        ttd_country: "%%TTD_COUNTRY%%",
        ttd_creativeid: "%%TTD_CREATIVEID%%",
        ttd_dealid: "%%TTD_DEALID%%",
        ttd_deviceosfamily: "%%TTD_DEVICEOSFAMILY%%",
        ttd_devicetype: "%%TTD_DEVICETYPE%%",
        ttd_devicemake: "%%TTD_DEVICEMAKE%%",
        ttd_devicemodel: "%%TTD_DEVICEMODEL%%",
        ttd_gdpr_applies: "%%TTD_GDPR_APPLIES%%",
        ttd_gdpr_consent_strinG: "%%TTD_GDPR_CONSENT_STRING%%",
        ttd_impressionid: "%%TTD_IMPRESSIONID%%",
        ttd_language: "%%TTD_LANGUAGE%%",
        ttd_metro: "%%TTD_METRO%%",
        ttd_partnerid: "%%TTD_PARTNERID%%",
        ttd_privatecontractid: "%%TTD_PRIVATECONTRACTID%%",
        ttd_publisherid: "%%TTD_PUBLISHERID%%",
        ttd_region: "%%TTD_REGION%%",
        ttd_rendering_context: "%%TTD_RENDERING_CONTEXT%%",
        ttd_site: "%%TTD_SITE%%",
        ttd_site_with_path: "%%TTD_SITE_WITH_PATH%%",
        ttd_supplyvendor: "%%TTD_SUPPLYVENDOR%%",
        ttd_tdid: "%%TTD_TDID%%",
        ttd_trustesid: "%%TTD_TRUSTESID%%",
        ttd_unix_timestamp: "%%TTD_UNIX_TIMESTAMP%%",
        ttd_zipcode: "%%TTD_ZIPCODE%%",
    },
    {
        game_key: "9f91161f43433ef7/9a6de6db680d70b6",
        lorenzo_id: "06210588-063d-4f36-ac44-53b265487380",
        region: "eu-west-1",
        environment: "MWEB",
        service_level: "managed",
        width: 320,
        height: 480,
        redirect_urls: [
            "%%TTD_CLK%%https://www.ocado.com/products/wash-with-leaf-non-bio-laundry-sheets-25-600151011",
        ],
        third_party_engagement: [],
        dsp: "TTD",
        ttd_imp_aud_user_ttl_min: "86400",
        ttd_adformat: "%%TTD_ADFORMAT%%",
        ttd_adgroupid: "%%TTD_ADGROUPID%%",
        ttd_advertiserid: "%%TTD_ADVERTISERID%%",
        ttd_all_categories: "%%TTD_ALL_CATEGORIES%%",
        ttd_base_bid_override_metadata: "%%TTD_BASE_BID_OVERRIDE_METADATA%%",
        ttd_campaignid: "%%TTD_CAMPAIGNID%%",
        ttd_category: "%%TTD_CATEGORY%%",
        ttd_city: "%%TTD_CITY%%",
        ttd_country: "%%TTD_COUNTRY%%",
        ttd_creativeid: "%%TTD_CREATIVEID%%",
        ttd_dealid: "%%TTD_DEALID%%",
        ttd_deviceosfamily: "%%TTD_DEVICEOSFAMILY%%",
        ttd_devicetype: "%%TTD_DEVICETYPE%%",
        ttd_devicemake: "%%TTD_DEVICEMAKE%%",
        ttd_devicemodel: "%%TTD_DEVICEMODEL%%",
        ttd_gdpr_applies: "%%TTD_GDPR_APPLIES%%",
        ttd_gdpr_consent_strinG: "%%TTD_GDPR_CONSENT_STRING%%",
        ttd_impressionid: "%%TTD_IMPRESSIONID%%",
        ttd_language: "%%TTD_LANGUAGE%%",
        ttd_metro: "%%TTD_METRO%%",
        ttd_partnerid: "%%TTD_PARTNERID%%",
        ttd_privatecontractid: "%%TTD_PRIVATECONTRACTID%%",
        ttd_publisherid: "%%TTD_PUBLISHERID%%",
        ttd_region: "%%TTD_REGION%%",
        ttd_rendering_context: "%%TTD_RENDERING_CONTEXT%%",
        ttd_site: "%%TTD_SITE%%",
        ttd_site_with_path: "%%TTD_SITE_WITH_PATH%%",
        ttd_supplyvendor: "%%TTD_SUPPLYVENDOR%%",
        ttd_tdid: "%%TTD_TDID%%",
        ttd_trustesid: "%%TTD_TRUSTESID%%",
        ttd_unix_timestamp: "%%TTD_UNIX_TIMESTAMP%%",
        ttd_zipcode: "%%TTD_ZIPCODE%%",
    },
    {
        game_key: "9f91161f43433ef7/9a6de6db680d70b7",
        lorenzo_id: "06210588-063d-4f36-ac44-53b265487380",
        region: "eu-west-1",
        environment: "MWEB",
        service_level: "managed",
        width: 320,
        height: 480,
        redirect_urls: [
            "%%TTD_CLK%%https://www.ocado.com/products/wash-with-leaf-non-bio-laundry-sheets-25-600151011",
        ],
        third_party_engagement: [],
        dsp: "TTD",
        ttd_imp_aud_user_ttl_min: "86400",
        ttd_adformat: "%%TTD_ADFORMAT%%",
        ttd_adgroupid: "%%TTD_ADGROUPID%%",
        ttd_advertiserid: "%%TTD_ADVERTISERID%%",
        ttd_all_categories: "%%TTD_ALL_CATEGORIES%%",
        ttd_base_bid_override_metadata: "%%TTD_BASE_BID_OVERRIDE_METADATA%%",
        ttd_campaignid: "%%TTD_CAMPAIGNID%%",
        ttd_category: "%%TTD_CATEGORY%%",
        ttd_city: "%%TTD_CITY%%",
        ttd_country: "%%TTD_COUNTRY%%",
        ttd_creativeid: "%%TTD_CREATIVEID%%",
        ttd_dealid: "%%TTD_DEALID%%",
        ttd_deviceosfamily: "%%TTD_DEVICEOSFAMILY%%",
        ttd_devicetype: "%%TTD_DEVICETYPE%%",
        ttd_devicemake: "%%TTD_DEVICEMAKE%%",
        ttd_devicemodel: "%%TTD_DEVICEMODEL%%",
        ttd_gdpr_applies: "%%TTD_GDPR_APPLIES%%",
        ttd_gdpr_consent_strinG: "%%TTD_GDPR_CONSENT_STRING%%",
        ttd_impressionid: "%%TTD_IMPRESSIONID%%",
        ttd_language: "%%TTD_LANGUAGE%%",
        ttd_metro: "%%TTD_METRO%%",
        ttd_partnerid: "%%TTD_PARTNERID%%",
        ttd_privatecontractid: "%%TTD_PRIVATECONTRACTID%%",
        ttd_publisherid: "%%TTD_PUBLISHERID%%",
        ttd_region: "%%TTD_REGION%%",
        ttd_rendering_context: "%%TTD_RENDERING_CONTEXT%%",
        ttd_site: "%%TTD_SITE%%",
        ttd_site_with_path: "%%TTD_SITE_WITH_PATH%%",
        ttd_supplyvendor: "%%TTD_SUPPLYVENDOR%%",
        ttd_tdid: "%%TTD_TDID%%",
        ttd_trustesid: "%%TTD_TRUSTESID%%",
        ttd_unix_timestamp: "%%TTD_UNIX_TIMESTAMP%%",
        ttd_zipcode: "%%TTD_ZIPCODE%%",
    },
    {
        game_key: "9f91161f43433ef7/9a6de6db680d70b5",
        lorenzo_id: "06210588-063d-4f36-ac44-53b265487380",
        region: "eu-west-1",
        environment: "MWEB",
        service_level: "managed",
        width: 320,
        height: 480,
        redirect_urls: [
            "%%TTD_CLK%%https://www.ocado.com/products/wash-with-leaf-non-bio-laundry-sheets-25-600151011",
        ],
        third_party_engagement: [],
        dsp: "TTD",
        ttd_imp_aud_user_ttl_min: "86400",
        ttd_adformat: "%%TTD_ADFORMAT%%",
        ttd_adgroupid: "%%TTD_ADGROUPID%%",
        ttd_advertiserid: "%%TTD_ADVERTISERID%%",
        ttd_all_categories: "%%TTD_ALL_CATEGORIES%%",
        ttd_base_bid_override_metadata: "%%TTD_BASE_BID_OVERRIDE_METADATA%%",
        ttd_campaignid: "%%TTD_CAMPAIGNID%%",
        ttd_category: "%%TTD_CATEGORY%%",
        ttd_city: "%%TTD_CITY%%",
        ttd_country: "%%TTD_COUNTRY%%",
        ttd_creativeid: "%%TTD_CREATIVEID%%",
        ttd_dealid: "%%TTD_DEALID%%",
        ttd_deviceosfamily: "%%TTD_DEVICEOSFAMILY%%",
        ttd_devicetype: "%%TTD_DEVICETYPE%%",
        ttd_devicemake: "%%TTD_DEVICEMAKE%%",
        ttd_devicemodel: "%%TTD_DEVICEMODEL%%",
        ttd_gdpr_applies: "%%TTD_GDPR_APPLIES%%",
        ttd_gdpr_consent_strinG: "%%TTD_GDPR_CONSENT_STRING%%",
        ttd_impressionid: "%%TTD_IMPRESSIONID%%",
        ttd_language: "%%TTD_LANGUAGE%%",
        ttd_metro: "%%TTD_METRO%%",
        ttd_partnerid: "%%TTD_PARTNERID%%",
        ttd_privatecontractid: "%%TTD_PRIVATECONTRACTID%%",
        ttd_publisherid: "%%TTD_PUBLISHERID%%",
        ttd_region: "%%TTD_REGION%%",
        ttd_rendering_context: "%%TTD_RENDERING_CONTEXT%%",
        ttd_site: "%%TTD_SITE%%",
        ttd_site_with_path: "%%TTD_SITE_WITH_PATH%%",
        ttd_supplyvendor: "%%TTD_SUPPLYVENDOR%%",
        ttd_tdid: "%%TTD_TDID%%",
        ttd_trustesid: "%%TTD_TRUSTESID%%",
        ttd_unix_timestamp: "%%TTD_UNIX_TIMESTAMP%%",
        ttd_zipcode: "%%TTD_ZIPCODE%%",
    },
];
